version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.1.1

jobs:
  phpstan:
    docker:
      - image: cimg/php:8.0
    steps:
      # Checkout branch
      - checkout

      # Install Composer dependencies
      - restore_cache:
          key: composer-{{ checksum "composer.json" }}
      - run: composer install --ignore-platform-reqs
      - save_cache:
          key: composer-{{ checksum "composer.json" }}
          paths:
            - vendor

      # Create result folder
      - run: mkdir -p test-results/phpstan-result

      # Run code analysis with PHPStan
      - run: composer code-analyze-save-report

      # Save code analysis results
      - store_test_results:
          path: test-results
  phpcs:
    docker:
      - image: cimg/php:8.0
    steps:
      # Checkout branch
      - checkout

      # Install Composer dependencies
      - restore_cache:
          key: composer-{{ checksum "composer.json" }}
      - run: composer install --ignore-platform-reqs
      - save_cache:
          key: composer-{{ checksum "composer.json" }}
          paths:
            - vendor

      # Create result folder
      - run: mkdir -p test-results/phpcs-result

      # Run code style check with PHP_CodeSniffer
      - run: composer check-format-save-report

      # Save code style check results
      - store_test_results:
          path: test-results
  build-phar:
    docker:
      - image: cimg/php:8.0
    steps:
      # Checkout branch
      - checkout

      # Install dependencies of PHP extensions
      - run: sudo apt-get update && sudo apt-get install -y libyaml-dev

      # Manually install PHP extensions
      - run: sudo pecl install yaml

      # Clone DevTools sources
      - run: git clone https://github.com/pmmp/DevTools.git

      # Create build output folder
      - run: mkdir -p build-output

      # Build PHAR with DevTools
      - run: php -d phar.readonly=0 DevTools/src/ConsoleScript.php --make plugin.yml,src,resources --out build-output/$CIRCLE_PROJECT_REPONAME$CIRCLE_SHA1.phar

      # Create workspace folder
      - run: mkdir -p workspace

      # Copy build output folder into workspace
      - run: cp -r build-output workspace/

      # Save workspace with built PHAR file for release job
      - persist_to_workspace:
          root: workspace
          paths:
            - build-output

      # Save built PHAR file as artifact
      - store_artifacts:
          path: build-output
  release-plugin:
    docker:
      - image: cimg/python:3.11-node
    steps:
      # Restore workspace with built PHAR file
      - attach_workspace:
          at: /tmp/workspace

      # Rename PHAR file to release name
      - run: cp /tmp/workspace/build-output/$CIRCLE_PROJECT_REPONAME$CIRCLE_SHA1.phar /tmp/workspace/build-output/$CIRCLE_PROJECT_REPONAME$CIRCLE_TAG.phar

      # Upload files to AWS S3
      - aws-s3/copy:
          from: /tmp/workspace/build-output/$CIRCLE_PROJECT_REPONAME$CIRCLE_TAG.phar
          to: "s3://static.surva.net/osplugins/dl/"

      # Update plugin info in CMS
      - run: |
          curl --location --request PATCH "$CONTENT_URL/items/plugin_info/$PL_INFO_ID" \
            --header "Authorization: Bearer $CONTENT_TOKEN" \
            --header "Content-Type: application/json" \
            --data-raw "{\"version\": \"$CIRCLE_TAG\",\"download_url\": \"https://static.surva.net/osplugins/dl/$CIRCLE_PROJECT_REPONAME$CIRCLE_TAG.phar\"}"

workflows:
  version: 2
  code_checks:
    jobs:
      - phpstan
      - phpcs
  deploy:
    jobs:
      - build-phar:
          filters:
            tags:
              only: /.*/
      - release-plugin:
          context: os-plugins-deploy
          requires:
            - build-phar
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
