# __        __         _     _
# \ \      / /__  _ __| | __| |___
#  \ \ /\ / / _ \| '__| |/ _` / __|
#   \ V  V / (_) | |  | | (_| \__ \
#    \_/\_/ \___/|_|  |_|\__,_|___/
#
# (C) 2019 by surva network | https://github.com/survanetwork

# Language of the plugin messages
# Possible options are: en (English), de (German), zh (Chinese), id (Indonesian), lv (Latvian), fr (French), tr (Turkish), ja (Japanese), vi (Vietnamese)
language: "en"

# Try to automatically detect the player's language and send translated messages for each player
# (language set above is used if player's language can't be detected)
autodetectlanguage: true

# Automatically convert worlds into the default format when loading an unsupported format
autoupgradeformat: true
