# __        __         _     _
# \ \      / /__  _ __| | __| |___
#  \ \ /\ / / _ \| '__| |/ _` / __|
#   \ V  V / (_) | |  | | (_| \__ \
#    \_/\_/ \___/|_|  |_|\__,_|___/
#
# (C) 2019 by surva network | https://github.com/survanetwork

# Language of the plugin messages
# Possible options are: en (English), de (German), zh (Chinese)
language: "en"
